import type { Property, Agent, AfricanCountry, Testimonial, Stat, InfrastructureProject } from '@/types';

export const FEATURED_PROPERTIES: Property[] = [
  {
    id: 'prop-001',
    title: 'The Pinnacle Penthouse, Ikoyi',
    description: 'An ultra-luxury penthouse redefining skyline living in Lagos\'s most prestigious address. Floor-to-ceiling glass, private infinity pool, and panoramic views of Victoria Island.',
    type: 'penthouse',
    status: 'for-sale',
    price: 4500000,
    currency: 'USD',
    bedrooms: 5,
    bathrooms: 6,
    size: 850,
    sizeUnit: 'sqm',
    location: { address: '14 Bourdillon Road, Ikoyi', city: 'Lagos', country: 'Nigeria', coordinates: { lat: 6.4530, lng: 3.4337 } },
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1200&q=80',
    ],
    amenities: ['Private Pool', 'Gym', 'Smart Home', 'Concierge', 'Wine Cellar', 'Cinema Room', 'Helipad Access', '24/7 Security'],
    agent: { id: 'agent-001', name: 'Adaeze Okonkwo', title: 'Luxury Property Specialist', agency: '4zee Elite Lagos', avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=200&q=80', phone: '+234 801 234 5678', email: 'adaeze@4zee.com', whatsapp: '+2348012345678', rating: 4.9, reviews: 127, listings: 34, sold: 89, experience: 12, countries: ['Nigeria', 'Ghana'], verified: true, languages: ['English', 'Igbo', 'Yoruba'], bio: 'Luxury real estate specialist with 12 years in Nigerian premium markets.' },
    featured: true,
    luxury: true,
    yearBuilt: 2023,
    floors: 2,
    parking: 4,
    tags: ['Penthouse', 'Sea View', 'Smart Home', 'New Build'],
    views: 4821,
    savedCount: 312,
    createdAt: '2024-01-15',
  },
  {
    id: 'prop-002',
    title: 'Nairobi Sky Residence, Westlands',
    description: 'Contemporary luxury apartments in Nairobi\'s thriving Westlands district. Premium finishes, smart automation, and sweeping views of the Ngong Hills.',
    type: 'apartment',
    status: 'for-sale',
    price: 850000,
    currency: 'USD',
    bedrooms: 3,
    bathrooms: 3,
    size: 220,
    sizeUnit: 'sqm',
    location: { address: 'The Oval, Westlands', city: 'Nairobi', country: 'Kenya', coordinates: { lat: -1.2667, lng: 36.8038 } },
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
    ],
    amenities: ['Rooftop Pool', 'Co-working Space', 'EV Charging', 'Gym', 'Concierge', 'Smart Security'],
    agent: { id: 'agent-002', name: 'James Mwangi', title: 'Senior Property Consultant', agency: '4zee Properties Nairobi', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80', phone: '+254 700 123 456', email: 'james@4zee.com', whatsapp: '+254700123456', rating: 4.8, reviews: 94, listings: 28, sold: 67, experience: 9, countries: ['Kenya', 'Uganda', 'Tanzania'], verified: true, languages: ['English', 'Swahili'], bio: 'East Africa\'s trusted luxury property expert.' },
    featured: true,
    luxury: true,
    yearBuilt: 2023,
    floors: 1,
    parking: 2,
    tags: ['Hill View', 'Smart Home', 'New Development'],
    views: 3210,
    savedCount: 198,
    createdAt: '2024-02-01',
  },
  {
    id: 'prop-003',
    title: 'Sandton Crown Estate, Johannesburg',
    description: 'Exquisite private estate in the heart of Africa\'s richest square mile. Championship golf course access, private security village, and world-class architecture.',
    type: 'estate',
    status: 'for-sale',
    price: 6200000,
    currency: 'USD',
    bedrooms: 8,
    bathrooms: 9,
    size: 2400,
    sizeUnit: 'sqm',
    location: { address: 'Hyde Park Estate, Sandton', city: 'Johannesburg', country: 'South Africa', coordinates: { lat: -26.1067, lng: 28.0570 } },
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
    ],
    amenities: ['Olympic Pool', 'Tennis Court', 'Home Cinema', 'Wine Cellar', 'Staff Quarters', 'Helipad', 'Smart Security', 'Golf Access'],
    agent: { id: 'agent-003', name: 'Samantha van der Berg', title: 'Luxury Estate Director', agency: '4zee Elite SA', avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&q=80', phone: '+27 11 234 5678', email: 'samantha@4zee.com', whatsapp: '+27112345678', rating: 5.0, reviews: 203, listings: 45, sold: 134, experience: 18, countries: ['South Africa', 'Zimbabwe', 'Botswana'], verified: true, languages: ['English', 'Afrikaans', 'Zulu'], bio: 'South Africa\'s most awarded luxury estate specialist.' },
    featured: true,
    luxury: true,
    yearBuilt: 2020,
    floors: 3,
    parking: 8,
    tags: ['Estate', 'Golf', 'Helipad', 'Ultra Luxury'],
    views: 6721,
    savedCount: 445,
    createdAt: '2024-01-08',
  },
  {
    id: 'prop-004',
    title: 'Accra Marina Tower, Airport City',
    description: 'Ghana\'s most prestigious commercial and residential tower. Stunning Marina views, premium offices, and luxury residences with world-class amenities.',
    type: 'apartment',
    status: 'for-rent',
    price: 12000,
    currency: 'USD',
    bedrooms: 4,
    bathrooms: 4,
    size: 380,
    sizeUnit: 'sqm',
    location: { address: 'Marina Drive, Airport City', city: 'Accra', country: 'Ghana', coordinates: { lat: 5.6037, lng: -0.1870 } },
    images: [
      'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?w=1200&q=80',
      'https://images.unsplash.com/photo-1594484208280-efa00f96fc21?w=1200&q=80',
    ],
    amenities: ['Marina View', 'Pool', 'Gym', 'Concierge', 'Smart Home', '24/7 Security', 'Restaurant'],
    agent: { id: 'agent-004', name: 'Kwame Asante', title: 'Commercial Property Expert', agency: '4zee Ghana', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80', phone: '+233 20 123 4567', email: 'kwame@4zee.com', whatsapp: '+233201234567', rating: 4.7, reviews: 76, listings: 22, sold: 54, experience: 7, countries: ['Ghana', 'Ivory Coast'], verified: true, languages: ['English', 'Twi', 'French'], bio: 'Ghana\'s go-to expert for premium property investments.' },
    featured: true,
    luxury: true,
    yearBuilt: 2022,
    floors: 1,
    parking: 3,
    tags: ['Marina View', 'Smart Home', 'Premium Rental'],
    views: 2890,
    savedCount: 167,
    createdAt: '2024-03-01',
  },
  {
    id: 'prop-005',
    title: 'Abuja Heritage Villa, Maitama',
    description: 'Majestic diplomatic-grade villa in Abuja\'s most exclusive zone. Sprawling gardens, private pool, and bespoke interiors designed for the discerning elite.',
    type: 'villa',
    status: 'for-sale',
    price: 2800000,
    currency: 'USD',
    bedrooms: 7,
    bathrooms: 8,
    size: 1650,
    sizeUnit: 'sqm',
    location: { address: 'Maitama District', city: 'Abuja', country: 'Nigeria', coordinates: { lat: 9.0765, lng: 7.4983 } },
    images: [
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200&q=80',
      'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1200&q=80',
    ],
    amenities: ['Private Pool', 'Garden', 'Cinema', 'Guest House', 'Solar Power', 'BQ', 'Smart Security', 'Generator'],
    agent: { id: 'agent-001', name: 'Adaeze Okonkwo', title: 'Luxury Property Specialist', agency: '4zee Elite Lagos', avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=200&q=80', phone: '+234 801 234 5678', email: 'adaeze@4zee.com', whatsapp: '+2348012345678', rating: 4.9, reviews: 127, listings: 34, sold: 89, experience: 12, countries: ['Nigeria', 'Ghana'], verified: true, languages: ['English', 'Igbo', 'Yoruba'], bio: 'Luxury real estate specialist.' },
    featured: false,
    luxury: true,
    yearBuilt: 2019,
    floors: 2,
    parking: 6,
    tags: ['Diplomatic Zone', 'Villa', 'Garden', 'Solar'],
    views: 3341,
    savedCount: 221,
    createdAt: '2024-02-14',
  },
  {
    id: 'prop-006',
    title: 'Cairo Smart City Apartment, New Administrative Capital',
    description: 'Premium smart city apartments in Egypt\'s new capital, an urban marvel of modern architecture. Eco-friendly, connected, and investment-grade.',
    type: 'apartment',
    status: 'off-plan',
    price: 320000,
    currency: 'USD',
    bedrooms: 3,
    bathrooms: 2,
    size: 165,
    sizeUnit: 'sqm',
    location: { address: 'R7 District, New Capital', city: 'Cairo', country: 'Egypt', coordinates: { lat: 30.0444, lng: 31.2357 } },
    images: [
      'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=1200&q=80',
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80',
    ],
    amenities: ['Smart Home', 'Community Pool', 'EV Charging', 'Solar Panels', 'Gym', 'Security'],
    agent: { id: 'agent-005', name: 'Omar Khalil', title: 'Investment Property Advisor', agency: '4zee Egypt', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&q=80', phone: '+20 10 1234 5678', email: 'omar@4zee.com', whatsapp: '+201012345678', rating: 4.8, reviews: 89, listings: 31, sold: 62, experience: 10, countries: ['Egypt', 'Morocco', 'Tunisia'], verified: true, languages: ['Arabic', 'English', 'French'], bio: 'North Africa\'s leading investment property advisor.' },
    featured: false,
    luxury: false,
    yearBuilt: 2025,
    floors: 1,
    parking: 1,
    tags: ['Smart City', 'Off-Plan', 'Investment', 'New Capital'],
    views: 5123,
    savedCount: 387,
    createdAt: '2024-03-15',
  },
];

export const AFRICAN_COUNTRIES: AfricanCountry[] = [
  { name: 'Nigeria', code: 'NG', flag: '🇳🇬', properties: 8421, agents: 342, avgPrice: '$450K', currency: 'NGN', growth: '+23%', featured: true, coordinates: { lat: 9.0820, lng: 8.6753 } },
  { name: 'South Africa', code: 'ZA', flag: '🇿🇦', properties: 12340, agents: 521, avgPrice: '$280K', currency: 'ZAR', growth: '+18%', featured: true, coordinates: { lat: -30.5595, lng: 22.9375 } },
  { name: 'Kenya', code: 'KE', flag: '🇰🇪', properties: 5680, agents: 234, avgPrice: '$180K', currency: 'KES', growth: '+31%', featured: true, coordinates: { lat: 0.0236, lng: 37.9062 } },
  { name: 'Ghana', code: 'GH', flag: '🇬🇭', properties: 3210, agents: 156, avgPrice: '$220K', currency: 'GHS', growth: '+27%', featured: true, coordinates: { lat: 7.9465, lng: -1.0232 } },
  { name: 'Egypt', code: 'EG', flag: '🇪🇬', properties: 9870, agents: 412, avgPrice: '$95K', currency: 'EGP', growth: '+35%', featured: true, coordinates: { lat: 26.8206, lng: 30.8025 } },
  { name: 'Morocco', code: 'MA', flag: '🇲🇦', properties: 4320, agents: 198, avgPrice: '$130K', currency: 'MAD', growth: '+22%', featured: false, coordinates: { lat: 31.7917, lng: -7.0926 } },
  { name: 'Tanzania', code: 'TZ', flag: '🇹🇿', properties: 1890, agents: 89, avgPrice: '$120K', currency: 'TZS', growth: '+28%', featured: false, coordinates: { lat: -6.3690, lng: 34.8888 } },
  { name: 'Ethiopia', code: 'ET', flag: '🇪🇹', properties: 2340, agents: 112, avgPrice: '$85K', currency: 'ETB', growth: '+42%', featured: false, coordinates: { lat: 9.1450, lng: 40.4897 } },
  { name: 'Ivory Coast', code: 'CI', flag: '🇨🇮', properties: 1560, agents: 74, avgPrice: '$160K', currency: 'XOF', growth: '+33%', featured: false, coordinates: { lat: 7.5400, lng: -5.5471 } },
  { name: 'Rwanda', code: 'RW', flag: '🇷🇼', properties: 980, agents: 45, avgPrice: '$145K', currency: 'RWF', growth: '+51%', featured: false, coordinates: { lat: -1.9403, lng: 29.8739 } },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-001',
    name: 'Chidi Okafor',
    role: 'CEO, Meridian Capital Partners',
    company: 'Lagos, Nigeria',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80',
    rating: 5,
    text: '4zee Properties transformed our real estate portfolio. The platform\'s AI recommendations led us to three exceptional acquisitions in Ikoyi and Victoria Island that have already appreciated 40% in 18 months. Truly world-class.',
    country: 'Nigeria',
    propertyType: 'Commercial',
  },
  {
    id: 'test-002',
    name: 'Amira Hassan',
    role: 'Investment Director',
    company: 'Cairo Investment Fund',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80',
    rating: 5,
    text: 'Finding premium property in Egypt\'s New Administrative Capital seemed overwhelming until 4zee. Their team guided us through every step, and the off-plan investment has already generated incredible returns.',
    country: 'Egypt',
    propertyType: 'Residential',
  },
  {
    id: 'test-003',
    name: 'David Kimani',
    role: 'Tech Entrepreneur',
    company: 'Nairobi, Kenya',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80',
    rating: 5,
    text: 'The virtual tour feature alone saved me three weeks of physical visits. I purchased my Westlands penthouse entirely through 4zee\'s platform, from initial search to final paperwork. Exceptional experience.',
    country: 'Kenya',
    propertyType: 'Penthouse',
  },
  {
    id: 'test-004',
    name: 'Thandi Nkosi',
    role: 'Property Investment Manager',
    company: 'Johannesburg, South Africa',
    avatar: 'https://images.unsplash.com/photo-1569913486515-b74bf7751574?w=200&q=80',
    rating: 5,
    text: '4zee\'s Africa-wide coverage is unmatched. We\'ve listed properties across six countries through one platform. The agent verification system and transaction transparency are exactly what the African market needed.',
    country: 'South Africa',
    propertyType: 'Multi-Country Portfolio',
  },
];

export const STATS: Stat[] = [
  { label: 'Properties Listed', value: 48750, suffix: '+', description: 'Across 28 African countries' },
  { label: 'Active Agents', value: 3200, suffix: '+', description: 'Verified professionals' },
  { label: 'Countries Covered', value: 28, suffix: '', description: 'Pan-African presence' },
  { label: 'Successful Deals', value: 14500, suffix: '+', description: 'Total transactions completed' },
];

export const INFRASTRUCTURE_PROJECTS: InfrastructureProject[] = [
  {
    id: 'inf-001',
    title: 'Eko Atlantic City',
    location: 'Victoria Island',
    country: 'Nigeria',
    type: 'Smart City Development',
    value: '$6 Billion',
    status: 'Under Construction',
    completion: '2030',
    image: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
    description: 'Africa\'s most ambitious smart city project built on reclaimed land off Lagos coastline.',
  },
  {
    id: 'inf-002',
    title: 'Tatu City',
    location: 'Kiambu County',
    country: 'Kenya',
    type: 'Integrated City',
    value: '$3.5 Billion',
    status: 'Phase 2 Active',
    completion: '2028',
    image: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80',
    description: 'Kenya\'s largest private integrated city with homes, schools, parks, and businesses.',
  },
  {
    id: 'inf-003',
    title: 'New Administrative Capital',
    location: 'Cairo Desert',
    country: 'Egypt',
    type: 'Government Capital City',
    value: '$58 Billion',
    status: 'Phase 1 Complete',
    completion: '2027',
    image: 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?w=800&q=80',
    description: 'Egypt\'s ambitious new capital city designed to house 7 million people.',
  },
  {
    id: 'inf-004',
    title: 'Diamniadio Smart City',
    location: 'Dakar Region',
    country: 'Senegal',
    type: 'Smart City',
    value: '$2.3 Billion',
    status: 'Active Development',
    completion: '2026',
    image: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800&q=80',
    description: 'West Africa\'s emerging smart city hub for tech and business.',
  },
];

export const PROPERTY_TYPES = [
  { value: '', label: 'All Types' },
  { value: 'apartment', label: 'Apartment' },
  { value: 'house', label: 'House' },
  { value: 'villa', label: 'Villa' },
  { value: 'penthouse', label: 'Penthouse' },
  { value: 'estate', label: 'Estate' },
  { value: 'commercial', label: 'Commercial' },
  { value: 'land', label: 'Land' },
  { value: 'office', label: 'Office' },
];

export const LISTING_STATUSES = [
  { value: '', label: 'Buy & Rent' },
  { value: 'for-sale', label: 'For Sale' },
  { value: 'for-rent', label: 'For Rent' },
  { value: 'for-lease', label: 'For Lease' },
  { value: 'off-plan', label: 'Off-Plan' },
];

export const AFRICAN_CITIES = [
  'Lagos', 'Abuja', 'Nairobi', 'Johannesburg', 'Cape Town', 'Cairo', 'Accra',
  'Dar es Salaam', 'Addis Ababa', 'Casablanca', 'Kigali', 'Abidjan', 'Dakar',
  'Luanda', 'Kampala', 'Lusaka', 'Harare', 'Maputo', 'Tunis', 'Tripoli',
];
